### ISSUE TITLE
Cannot assign pointer address at initialization

### ISSUE THREAD

**Issue by gregkrsak** [Mati365/ts-c-compiler#125]
The following code doesn't compile:
```c
/* PutPixel test */

#define VIDEO_MEMORY 0xa0000000

int main() {
  asm("mov ax, 0013h");
  asm("int 10h");

  volatile unsigned char *memory = (unsigned char *)VIDEO_MEMORY;
  
  register unsigned int x = 160;
  register unsigned int y = 100;
  
  y <<= 6;
  y <<= 8;
  x += y;
  
  memory[x] = 0x0f;
  
  return 0;
}
```

And gives the error:
```
(row: 9, col: 37): <Compiler> Cast to scalar type "<unknown-src-type>" to "unsigned char*" is not possible!
```

With the problem line being:
```c
volatile unsigned char *memory = (unsigned char *)VIDEO_MEMORY;
```

**Comment by Mati365** [comment]
Thx, I'll check that

**Comment by Mati365** [comment]
@gregkrsak It's not the bug but incorrect number size.  `0xa0000000` is larger than 16bit and compiler cannot assign proper type to it. At this moment, the compiler does not support far pointers and setting values in different segments must be done using `asm()` builtin function like in this place: https://github.com/Mati365/ts-c-compiler/blob/main/packages/compiler-pico-c/src/fs/kernel/kernel.h.ts#L43

**Comment by gregkrsak** [comment]
Understood. Thank you for the quick response!
