### ISSUE TITLE
How?

### ISSUE THREAD

**Issue by UserNotfoundR** [Mati365/ts-c-compiler#127]
Hello, I would like to know how to convert Python code to Assembly. I am working on a compilation for Python and need to understand how to perform this conversion. Could you share information about the process of converting C code to Assembly that you used in this compiler?

**Comment by Mati365** [comment]
It's almost impossible to translate python to C due to its dynamic typing system. Fristly you have to tokenize your code, then build AST, then assign types to such AST and then perform AST translation.

**Comment by UserNotfoundR** [comment]
I will try to create the python AST to convert to assembly.
